[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
rustflags = [
  # "-C", "link-arg=-Tmemory.x",
]

[env]
DEFMT_LOG = "trace"

[profile.dev]
debug = true

[profile.release]
debug = true  